<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="14405" started-at="2021-10-24T12:11:23 IST" finished-at="2021-10-24T12:11:37 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="14405" started-at="2021-10-24T12:11:23 IST" finished-at="2021-10-24T12:11:37 IST">
      <class name="testClasses.vilas.SanityTests">
        <test-method status="PASS" signature="beforclass()[pri:0, instance:testClasses.vilas.SanityTests@6c3708b3]" name="beforclass" is-config="true" duration-ms="4402" started-at="2021-10-24T12:11:23 IST" finished-at="2021-10-24T12:11:27 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforclass -->
        <test-method status="FAIL" signature="loginLinkVerificationOnHomePage()[pri:0, instance:testClasses.vilas.SanityTests@6c3708b3]" name="loginLinkVerificationOnHomePage" duration-ms="9937" started-at="2021-10-24T12:11:27 IST" finished-at="2021-10-24T12:11:37 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Actual value is not matching expected [Sign In] but found [Sign in]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Actual value is not matching expected [Sign In] but found [Sign in]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at testClasses.vilas.SanityTests.loginLinkVerificationOnHomePage(SanityTests.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginLinkVerificationOnHomePage -->
      </class> <!-- testClasses.vilas.SanityTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
